### ISSUE TITLE
taskgraph should not automatically store return value unless specified

### ISSUE THREAD

**Issue by richpsharp** [natcap/taskgraph#23]
When taskgraph attempts to store a return value that is not needed it creates space in the database as and in some cases raise an exception of the result cannot be explicitly pickled. Perhaps the default can be to not store the return result and raise an exception on a call to `.get()` or otherwise set a flag on `add_task`.

**Comment by dcdenu4** [comment]
Is there a use case where I would add a task that does not have a `target_path_list` and where I would not want a return value saved? I'm thinking: if not `target_path_list` then store the return, otherwise, what's the use case for calling the task? I'm sure there is one, just curious!

**Comment by richpsharp** [comment]
Good question. Something in a system call? Like authenticating `gsutil`? The value returned is something that we could store without an exception, but we wouldn't want it. The reverse might be more common: a function that modifies files and also returns a useful value. Like hashing a file that renames that file but we also want the digest rather than parsing it out of the filename? Either way, I like the explicitness of a flag rather than a side effect.
