### ISSUE TITLE
API reference

### ISSUE THREAD

**Issue by mcejp** [natcap/taskgraph#62]
Hi, is there any documentation of the API, besides the examples?

Thanks.

**Comment by emlys** [comment]
Not that I know of, @richpsharp might have something. 
taskgraph is maintained to support natcap/invest. As far as I know we are the only ones that use it, so an API reference has been low priority. Out of curiosity, what's your use case for taskgraph?

**Comment by richpsharp** [comment]
We keep very detailed docstrings which you might find useful @mcejp, but we aren't planning to support other documentation of the API at the moment. For example, https://github.com/natcap/taskgraph/blob/main/taskgraph/Task.py#L573 documents the `add_task` arguments.

**Comment by mcejp** [comment]
Ok, understandable. I'll try to see how easy it is to auto-generate something readable from the dosctrings, even if you're not interested in supporting it officially.

@emlys i found the package on PyPi. I'm using it as "`make` but it's a Python library", to bake assets for a game. I found it to be a much better impedance match for my tool than other popular task queues like [huey](https://github.com/coleifer/huey), since you don't need to manually manage task executors, don't need to worry about configuring serialization/transport/database, and because the task model is fundamentally very similar to `make` (dependencies forming a DAG + lazy processing)

**Comment by richpsharp** [comment]
Okay thank you @mcejp! Happy to review a PR if you find something easy to maintain regarding documentation. I'm going to close this issue for now but feel free to reopen if you do want to address that, or if you can't reopen it (I'm not sure what the permission rules are) you can open a new issue or link it in your PR and I'll adjust it accordingly.
