### ISSUE TITLE
Also test against python 3.9

### ISSUE THREAD

**Issue by phargogh** [natcap/taskgraph#72]
Python 3.9 is the latest available, so we should make sure that taskgraph works as expected in python 3.9.

**Comment by mcejp** [comment]
FYI, [Python 3.10 is out next week](https://www.python.org/downloads/release/python-3100rc2/), it might be useful to already try and include it :)

**Comment by phargogh** [comment]
Good point @mcejp !  Let's track python 3.10 support over in #78
